### ISSUE TITLE
Increase errorCheck frozen and queueFail trigger time to 30 seconds

### ISSUE THREAD

**Issue by PDStig** [Lovinity/wwsu#51]
Increase the trigger time for queueFrozen and queueFail from 10 seconds to 30 seconds to accommodate the RadioDJ freeze-ups during playlist queuing.

Ref: https://github.com/Lovinity/wwsu/issues/49

- [x] Implement

- [x] Monitor

**Comment by Lovinity** [comment]
it's called frozen, not queueFrozen... and the increase is from 15 to 30 seconds, not 10 to 30 seconds.
